export { apiClient, ApiError, unwrap } from "./client";
export * as authApi from "./auth";
export * as eldersApi from "./elders";
export * as dashboardApi from "./dashboard";
export * as diseasesApi from "./diseases";
export * as medicationsApi from "./medications";
export * as healthNoteApi from "./healthNote";
export * as checkinApi from "./checkin";
export * as guardiansApi from "./guardians";
export * as conversationsApi from "./conversations";
export * as remindersApi from "./reminders";
export * as documentsApi from "./documents";
